// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFSxVlz288BdrO4P98cTzKMWgSMjJ8hI',
    appId: '1:506803512034:web:9e5f9646043ae14321b4bb',
    messagingSenderId: '506803512034',
    projectId: 'to-do-app-d4230',
    authDomain: 'to-do-app-d4230.firebaseapp.com',
    storageBucket: 'to-do-app-d4230.appspot.com',
    measurementId: 'G-C6E1JMBKCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEtcXI0AbJuL_V79hzoHcUFYwRQ6-4VUY',
    appId: '1:506803512034:android:7362c6a2b342310e21b4bb',
    messagingSenderId: '506803512034',
    projectId: 'to-do-app-d4230',
    storageBucket: 'to-do-app-d4230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_0dFzI9gBYV3pWEVCAUGsSRUjQS8rW-U',
    appId: '1:506803512034:ios:80944fcb7840f67b21b4bb',
    messagingSenderId: '506803512034',
    projectId: 'to-do-app-d4230',
    storageBucket: 'to-do-app-d4230.appspot.com',
    iosBundleId: 'com.example.session10Flutter6Todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_0dFzI9gBYV3pWEVCAUGsSRUjQS8rW-U',
    appId: '1:506803512034:ios:4cce69b3cdcf784421b4bb',
    messagingSenderId: '506803512034',
    projectId: 'to-do-app-d4230',
    storageBucket: 'to-do-app-d4230.appspot.com',
    iosBundleId: 'com.example.session10Flutter6Todo.RunnerTests',
  );
}
